ALTER TABLE users
    MODIFY password VARCHAR(255) NULL;

ALTER TABLE patients
    DROP PRIMARY KEY,
    ADD COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST,
    MODIFY user_id INT NOT NULL,
    ADD UNIQUE KEY uq_patients_user_id (user_id),
    DROP COLUMN age,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS date_of_birth DATE NULL,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10) NULL,
    ADD COLUMN IF NOT EXISTS height FLOAT NULL,
    ADD COLUMN IF NOT EXISTS weight FLOAT NULL;
